name: Go Code Coverage
  # You may pin to the exact commit or the version.
  # uses: Sonichigo/go-covreport@ced15002abdec0c8dfb939973312dce8d1ba5670
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      uses: Sonichigo/go-covreport@v1
      with:
        package: ./..
          
